Show in dialog box, details regarding the Github commits (#26)
damdiana/github-api pull request #28
Opened 2023-02-22 14:34 UTC by damdiana

2023-02-23 11:31 UTC, damdiana commented
Details regarding the commits:

commit message (as a commit title)
author
commit date

2023-02-24 09:25 UTC, iampava requested changes

2023-02-24 09:25 UTC, iampava commented on src/GithubApi.ts
> +
Please remove the newline...

2023-02-24 09:25 UTC, iampava commented on src/app.ts
> +
What is this?

2023-02-24 09:25 UTC, iampava commented on src/app.ts
> +    commits.forEach(commit => {
You should use the sorted commits Array: `descendingCommitsByDate`

2023-02-24 09:25 UTC, iampava commented on src/style/style.css
> +}
What is this?

2023-02-24 09:53 UTC, iampava requested changes

2023-02-24 09:53 UTC, iampava commented on src/style/buttons.css
> +.btn--bottom-outline {
THis should be on the `tab` class, not a special kind of butotn.

2023-02-24 09:56 UTC, iampava approved these changes

2023-02-24 09:58 UTC, merged